import { VocabWord } from './types';

// Helper to generate IDs
const generateId = () => Math.random().toString(36).substr(2, 9);

// Data derived from user request
export const VOCABULARY_DATA: VocabWord[] = [
  // TEAMMS 4, Lesson 8
  { id: generateId(), team: "TEAMMS 4", lesson: "Lesson 8", english: "mango", chinese: "芒果" },
  { id: generateId(), team: "TEAMMS 4", lesson: "Lesson 8", english: "tangerine", chinese: "橘子" },
  { id: generateId(), team: "TEAMMS 4", lesson: "Lesson 8", english: "plum", chinese: "梅子" },
  { id: generateId(), team: "TEAMMS 4", lesson: "Lesson 8", english: "grapefruit", chinese: "葡萄柚" },
  { id: generateId(), team: "TEAMMS 4", lesson: "Lesson 8", english: "honeydew", chinese: "甘露" },
  { id: generateId(), team: "TEAMMS 4", lesson: "Lesson 8", english: "cantaloupe", chinese: "哈密瓜" },
  { id: generateId(), team: "TEAMMS 4", lesson: "Lesson 8", english: "blueberry", chinese: "藍莓" },
  { id: generateId(), team: "TEAMMS 4", lesson: "Lesson 8", english: "raspberry", chinese: "覆盆子" },
  { id: generateId(), team: "TEAMMS 4", lesson: "Lesson 8", english: "passion fruit", chinese: "百香果" },
  { id: generateId(), team: "TEAMMS 4", lesson: "Lesson 8", english: "lime", chinese: "酸橙" },
  
  // TEAMMS 4, Lesson 9
  { id: generateId(), team: "TEAMMS 4", lesson: "Lesson 9", english: "potato", chinese: "馬鈴薯" },
  { id: generateId(), team: "TEAMMS 4", lesson: "Lesson 9", english: "carrot", chinese: "紅蘿蔔" },
  { id: generateId(), team: "TEAMMS 4", lesson: "Lesson 9", english: "onion", chinese: "洋蔥" },
  { id: generateId(), team: "TEAMMS 4", lesson: "Lesson 9", english: "mushroom", chinese: "香菇" },
  { id: generateId(), team: "TEAMMS 4", lesson: "Lesson 9", english: "tomato", chinese: "番茄" },
  { id: generateId(), team: "TEAMMS 4", lesson: "Lesson 9", english: "cucumber", chinese: "黃瓜" },
  { id: generateId(), team: "TEAMMS 4", lesson: "Lesson 9", english: "pumpkin", chinese: "南瓜" },
  { id: generateId(), team: "TEAMMS 4", lesson: "Lesson 9", english: "lettuce", chinese: "萵苣" },
  { id: generateId(), team: "TEAMMS 4", lesson: "Lesson 9", english: "cabbage", chinese: "高麗菜" },
  { id: generateId(), team: "TEAMMS 4", lesson: "Lesson 9", english: "corn", chinese: "玉米" },

  // TEAMMS 4, Lesson 10
  { id: generateId(), team: "TEAMMS 4", lesson: "Lesson 10", english: "buy", chinese: "買" },
  { id: generateId(), team: "TEAMMS 4", lesson: "Lesson 10", english: "read", chinese: "閱讀" },
  { id: generateId(), team: "TEAMMS 4", lesson: "Lesson 10", english: "write", chinese: "寫" },
  { id: generateId(), team: "TEAMMS 4", lesson: "Lesson 10", english: "chase", chinese: "追" },
  { id: generateId(), team: "TEAMMS 4", lesson: "Lesson 10", english: "draw", chinese: "畫畫" },
  { id: generateId(), team: "TEAMMS 4", lesson: "Lesson 10", english: "pick up", chinese: "撿起" },
  { id: generateId(), team: "TEAMMS 4", lesson: "Lesson 10", english: "skip", chinese: "跳躍" },
  { id: generateId(), team: "TEAMMS 4", lesson: "Lesson 10", english: "carry", chinese: "搬運" },
  { id: generateId(), team: "TEAMMS 4", lesson: "Lesson 10", english: "hide", chinese: "躲藏" },
  { id: generateId(), team: "TEAMMS 4", lesson: "Lesson 10", english: "pool", chinese: "游泳池" },

  // TEAMMS 4, Lesson 11
  { id: generateId(), team: "TEAMMS 4", lesson: "Lesson 11", english: "bus stop", chinese: "公車站" },
  { id: generateId(), team: "TEAMMS 4", lesson: "Lesson 11", english: "airport", chinese: "飛機場" },
  { id: generateId(), team: "TEAMMS 4", lesson: "Lesson 11", english: "farm", chinese: "農場" },
  { id: generateId(), team: "TEAMMS 4", lesson: "Lesson 11", english: "museum", chinese: "博物館" },
  { id: generateId(), team: "TEAMMS 4", lesson: "Lesson 11", english: "train station", chinese: "火車站" },
  { id: generateId(), team: "TEAMMS 4", lesson: "Lesson 11", english: "aquarium", chinese: "水族館" },
  { id: generateId(), team: "TEAMMS 4", lesson: "Lesson 11", english: "library", chinese: "圖書館" },
  { id: generateId(), team: "TEAMMS 4", lesson: "Lesson 11", english: "movie theater", chinese: "電影院" },
  { id: generateId(), team: "TEAMMS 4", lesson: "Lesson 11", english: "beach", chinese: "沙灘" },
  { id: generateId(), team: "TEAMMS 4", lesson: "Lesson 11", english: "zoo", chinese: "動物園" },

  // TEAMMS 4, Lesson 12
  { id: generateId(), team: "TEAMMS 4", lesson: "Lesson 12", english: "driving a van", chinese: "開貨車" },
  { id: generateId(), team: "TEAMMS 4", lesson: "Lesson 12", english: "riding a motorcycle", chinese: "騎摩托車" },
  { id: generateId(), team: "TEAMMS 4", lesson: "Lesson 12", english: "riding a bicycle", chinese: "騎腳踏車" },
  { id: generateId(), team: "TEAMMS 4", lesson: "Lesson 12", english: "riding a scooter", chinese: "騎機車" },
  { id: generateId(), team: "TEAMMS 4", lesson: "Lesson 12", english: "taking an airplane", chinese: "搭飛機" },
  { id: generateId(), team: "TEAMMS 4", lesson: "Lesson 12", english: "taking the bus", chinese: "搭公車" },
  { id: generateId(), team: "TEAMMS 4", lesson: "Lesson 12", english: "taking the subway", chinese: "搭地鐵" },
  { id: generateId(), team: "TEAMMS 4", lesson: "Lesson 12", english: "taking a ship", chinese: "搭郵輪" },
  { id: generateId(), team: "TEAMMS 4", lesson: "Lesson 12", english: "taking a boat", chinese: "搭船" },
  { id: generateId(), team: "TEAMMS 4", lesson: "Lesson 12", english: "taking a helicopter", chinese: "搭直升機" },

  // TEAMMS 5, Lesson 1
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 1", english: "salty", chinese: "鹹的" },
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 1", english: "greasy", chinese: "油膩的" },
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 1", english: "crunchy", chinese: "酥脆的" },
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 1", english: "juicy", chinese: "多汁的" },
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 1", english: "spicy", chinese: "辛辣的" },
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 1", english: "pork", chinese: "豬肉" },
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 1", english: "steak", chinese: "牛排" },
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 1", english: "beef", chinese: "牛肉" },
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 1", english: "ribs", chinese: "肋排" },
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 1", english: "peanuts", chinese: "花生" },

  // TEAMMS 5, Lesson 2
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 2", english: "toilet", chinese: "馬桶" },
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 2", english: "sink", chinese: "水槽" },
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 2", english: "bathtub", chinese: "浴缸" },
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 2", english: "faucet", chinese: "水龍頭" },
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 2", english: "mirror", chinese: "鏡子" },
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 2", english: "towel", chinese: "毛巾" },
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 2", english: "toothbrush", chinese: "牙刷" },
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 2", english: "toothpaste", chinese: "牙膏" },
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 2", english: "comb", chinese: "梳子" },
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 2", english: "hairbrush", chinese: "髮刷" },

  // TEAMMS 5, Lesson 3
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 3", english: "writing", chinese: "寫" },
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 3", english: "sleeping", chinese: "睡覺" },
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 3", english: "talking on the phone", chinese: "講電話" },
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 3", english: "listening to music", chinese: "聽音樂" },
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 3", english: "looking for something", chinese: "找東西" },
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 3", english: "doing homework", chinese: "寫功課" },
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 3", english: "watching a movie", chinese: "看電影" },
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 3", english: "watching TV", chinese: "看電視" },
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 3", english: "story", chinese: "故事" },
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 3", english: "letter", chinese: "信件" },

  // TEAMMS 5, Lesson 4
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 4", english: "on the corner", chinese: "在轉角" },
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 4", english: "across from", chinese: "從對面" },
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 4", english: "go straight", chinese: "直走" },
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 4", english: "turn left", chinese: "左轉" },
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 4", english: "turn right", chinese: "右轉" },
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 4", english: "go past", chinese: "走過去" },
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 4", english: "on the left", chinese: "在左邊" },
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 4", english: "block", chinese: "街區" },
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 4", english: "on the right", chinese: "在右邊" },
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 4", english: "go back", chinese: "回到" },

  // TEAMMS 5, Lesson 5
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 5", english: "lamb", chinese: "羊排" },
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 5", english: "cheese", chinese: "起司" },
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 5", english: "goat milk", chinese: "羊奶" },
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 5", english: "yogurt", chinese: "優格" },
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 5", english: "jam", chinese: "果醬" },
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 5", english: "ketchup", chinese: "番茄醬" },
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 5", english: "butter", chinese: "奶油" },
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 5", english: "soy sauce", chinese: "醬油" },
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 5", english: "the taste", chinese: "味道" },
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 5", english: "the smell", chinese: "氣味" },

  // TEAMMS 5, Lesson 6
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 6", english: "bake cookies", chinese: "烤餅乾" },
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 6", english: "watch cartoons", chinese: "看卡通" },
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 6", english: "browse the web", chinese: "瀏覽網頁" },
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 6", english: "play sports", chinese: "運動" },
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 6", english: "read comic books", chinese: "看漫畫" },
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 6", english: "read manga", chinese: "看漫畫" },
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 6", english: "talk with my friends", chinese: "跟朋友講話" },
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 6", english: "go jogging", chinese: "去慢跑" },
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 6", english: "go shopping", chinese: "去購物" },
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 6", english: "watch videos", chinese: "看影片" },

  // TEAMMS 5, Lesson 7
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 7", english: "Monday", chinese: "星期一" },
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 7", english: "Tuesday", chinese: "星期二" },
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 7", english: "Wednesday", chinese: "星期三" },
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 7", english: "Thursday", chinese: "星期四" },
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 7", english: "Friday", chinese: "星期五" },
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 7", english: "Saturday", chinese: "星期六" },
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 7", english: "Sunday", chinese: "星期日" },
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 7", english: "gym", chinese: "健身房" },
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 7", english: "hair salon", chinese: "髮廊" },
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 7", english: "arcade", chinese: "商場" },

  // TEAMMS 5, Lesson 8
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 8", english: "elevator", chinese: "電梯" },
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 8", english: "escalator", chinese: "手扶梯" },
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 8", english: "building", chinese: "建築物" },
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 8", english: "street", chinese: "街" },
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 8", english: "river", chinese: "河" },
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 8", english: "animals", chinese: "動物" },
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 8", english: "some", chinese: "一些" },
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 8", english: "several", chinese: "幾個" },
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 8", english: "a few", chinese: "很少" },
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 8", english: "lots of / a lot of", chinese: "很多" },

  // TEAMMS 5, Lesson 9
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 9", english: "frog", chinese: "青蛙" },
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 9", english: "ambulance", chinese: "救護車" },
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 9", english: "phone", chinese: "電話" },
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 9", english: "plant", chinese: "植物" },
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 9", english: "laptop", chinese: "筆電" },
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 9", english: "salt", chinese: "鹽" },
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 9", english: "camera", chinese: "相機" },
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 9", english: "sugar", chinese: "糖" },
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 9", english: "fire truck", chinese: "消防車" },
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 9", english: "paper", chinese: "紙" },

  // TEAMMS 5, Lesson 10
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 10", english: "a loaf of bread", chinese: "一條麵包" },
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 10", english: "a bag of chips", chinese: "一袋洋芋片" },
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 10", english: "a jar of honey", chinese: "一罐蜂蜜" },
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 10", english: "a box of chocolate", chinese: "一盒巧克力" },
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 10", english: "a bowl of rice", chinese: "一碗飯" },
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 10", english: "a package of vegetables", chinese: "一袋蔬菜" },
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 10", english: "a carton of ice cream", chinese: "一盒冰淇淋" },
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 10", english: "a glass of water", chinese: "一杯水" },
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 10", english: "a tube of toothpaste", chinese: "一條牙膏" },
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 10", english: "a can of soda", chinese: "一罐蘇打水" },

  // TEAMMS 5, Lesson 11
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 11", english: "jacket", chinese: "夾克" },
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 11", english: "gloves", chinese: "手套" },
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 11", english: "hoodie", chinese: "帶帽的運動衫" },
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 11", english: "scarf", chinese: "圍巾" },
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 11", english: "boots", chinese: "靴子" },
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 11", english: "raincoat", chinese: "雨衣" },
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 11", english: "sandals", chinese: "涼鞋" },
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 11", english: "mittens", chinese: "連指手套" },
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 11", english: "sunglasses", chinese: "太陽眼鏡" },
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 11", english: "cap", chinese: "帽子" },

  // TEAMMS 5, Lesson 12
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 12", english: "first (1st)", chinese: "第一" },
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 12", english: "second (2nd)", chinese: "第二" },
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 12", english: "third (3rd)", chinese: "第三" },
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 12", english: "fourth (4th)", chinese: "第四" },
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 12", english: "fifth (5th)", chinese: "第五" },
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 12", english: "sixth (6th)", chinese: "第六" },
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 12", english: "seventh (7th)", chinese: "第七" },
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 12", english: "eighth (8th)", chinese: "第八" },
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 12", english: "ninth (9th)", chinese: "第九" },
  { id: generateId(), team: "TEAMMS 5", lesson: "Lesson 12", english: "tenth (10th)", chinese: "第十" },

  // TEAMMS 6, Lesson 1
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 1", english: "basketball", chinese: "籃球" },
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 1", english: "golf", chinese: "高爾夫球" },
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 1", english: "baseball", chinese: "棒球" },
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 1", english: "table tennis (ping pong)", chinese: "桌球" },
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 1", english: "tennis", chinese: "網球" },
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 1", english: "badminton", chinese: "羽球" },
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 1", english: "soccer (football)", chinese: "足球" },
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 1", english: "hockey", chinese: "曲棍球" },
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 1", english: "volleyball", chinese: "排球" },
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 1", english: "rugby", chinese: "橄欖球" },

  // TEAMMS 6, Lesson 2
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 2", english: "shoot videos", chinese: "拍影片" },
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 2", english: "sew", chinese: "裁縫" },
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 2", english: "blog", chinese: "部落格" },
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 2", english: "write poetry", chinese: "寫詩" },
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 2", english: "practice magic tricks", chinese: "練習魔術" },
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 2", english: "take pictures", chinese: "拍照" },
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 2", english: "play chess", chinese: "下棋" },
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 2", english: "make jewelry", chinese: "做珠寶" },
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 2", english: "make scrapbooks", chinese: "製作剪貼簿" },
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 2", english: "edit videos / pictures", chinese: "編輯影片/圖片" },

  // TEAMMS 6, Lesson 3
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 3", english: "a quarter to", chinese: "每個小時的 45 分" },
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 3", english: "ten to", chinese: "剩 10 分鐘...整點" },
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 3", english: "minute", chinese: "分鐘" },
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 3", english: "a quarter past", chinese: "每個小時的 15 分" },
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 3", english: "o'clock", chinese: "...點整" },
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 3", english: "half past", chinese: "半小時" },
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 3", english: "hour", chinese: "小時" },
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 3", english: "class", chinese: "班/班級/課/課堂" },
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 3", english: "PM", chinese: "下午" },
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 3", english: "AM", chinese: "早上" },

  // TEAMMS 6, Lesson 4
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 4", english: "cafe", chinese: "咖啡廳" },
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 4", english: "eye clinic", chinese: "眼科診所" },
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 4", english: "skin clinic", chinese: "皮膚科診所" },
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 4", english: "bakery", chinese: "麵包店" },
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 4", english: "laundromat", chinese: "洗衣店" },
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 4", english: "farmers' market", chinese: "農民市集" },
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 4", english: "downtown", chinese: "市中心" },
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 4", english: "stationery store", chinese: "文具店" },
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 4", english: "dance studio", chinese: "舞蹈室" },
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 4", english: "tomorrow", chinese: "明天" },

  // TEAMMS 6, Lesson 5
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 5", english: "butterfly", chinese: "蝴蝶" },
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 5", english: "ant", chinese: "螞蟻" },
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 5", english: "fly", chinese: "蒼蠅" },
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 5", english: "insect", chinese: "昆蟲" },
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 5", english: "spider", chinese: "蜘蛛" },
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 5", english: "giraffe", chinese: "長頸鹿" },
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 5", english: "bee", chinese: "蜜蜂" },
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 5", english: "sheep", chinese: "綿羊" },
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 5", english: "hippo (hippopotamus)", chinese: "河馬" },
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 5", english: "rat", chinese: "老鼠" },

  // TEAMMS 6, Lesson 6
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 6", english: "big-bigger", chinese: "大的-更大的" },
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 6", english: "young-younger", chinese: "年輕的-更年輕的" },
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 6", english: "slow-slower", chinese: "慢的-更慢的" },
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 6", english: "small-smaller", chinese: "小的-更小的" },
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 6", english: "fast-faster", chinese: "快的-更快的" },
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 6", english: "dirty-dirtier", chinese: "髒的-更髒的" },
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 6", english: "old-older", chinese: "老的-更老的" },
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 6", english: "clean-cleaner", chinese: "乾淨的-更乾淨的" },
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 6", english: "short-shorter", chinese: "短的-更短的 / 矮的-更矮的" },
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 6", english: "tall-taller", chinese: "高的-更高的" },

  // TEAMMS 6, Lesson 7
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 7", english: "nice; nicer; nicest", chinese: "好的; 更好的; 最好的" },
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 7", english: "poor; poorer; poorest", chinese: "窮的; 更窮的; 最窮的" },
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 7", english: "close; closer; closest", chinese: "近的; 更近的; 最近的" },
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 7", english: "light; lighter; lightest", chinese: "輕的; 更輕的; 最輕的" },
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 7", english: "easy; easier; easiest", chinese: "簡單的; 更簡單的; 最簡單的" },
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 7", english: "cheap; cheaper; cheapest", chinese: "便宜的; 更便宜的; 最便宜的" },
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 7", english: "naughty; naughtier; naughtiest", chinese: "調皮的; 更調皮的; 最調皮的" },
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 7", english: "rich; richer; richest", chinese: "富有的; 更富有的; 最富有的" },
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 7", english: "heavy; heavier; heaviest", chinese: "重的; 更重的; 最重的" },
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 7", english: "silly; sillier; silliest", chinese: "愚蠢的; 更愚蠢的; 最愚蠢的" },

  // TEAMMS 6, Lesson 8
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 8", english: "too tight", chinese: "太緊" },
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 8", english: "too loose", chinese: "太鬆" },
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 8", english: "too short", chinese: "太短" },
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 8", english: "too long", chinese: "太長" },
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 8", english: "too big", chinese: "太大" },
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 8", english: "too small", chinese: "太小" },
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 8", english: "just right", chinese: "正好" },
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 8", english: "sneakers", chinese: "運動鞋" },
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 8", english: "necklace", chinese: "項鍊" },
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 8", english: "bracelet", chinese: "手環" },

  // TEAMMS 6, Lesson 9
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 9", english: "wipe the windows", chinese: "擦窗戶" },
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 9", english: "sweep the floor", chinese: "掃地" },
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 9", english: "vacuum the carpet", chinese: "吸塵地毯" },
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 9", english: "fold my clothes", chinese: "摺衣服" },
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 9", english: "take out the garbage", chinese: "倒垃圾" },
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 9", english: "hang my clothes", chinese: "晾衣服" },
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 9", english: "do the laundry", chinese: "洗衣服" },
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 9", english: "do the dishes", chinese: "洗碗" },
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 9", english: "mop the floor", chinese: "拖地" },
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 9", english: "dust the furniture", chinese: "打掃灰塵" },

  // TEAMMS 6, Lesson 10
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 10", english: "pocket", chinese: "口袋" },
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 10", english: "stool", chinese: "凳子" },
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 10", english: "ladder", chinese: "梯子" },
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 10", english: "roof", chinese: "屋頂" },
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 10", english: "rope", chinese: "繩子" },
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 10", english: "ground", chinese: "地面" },
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 10", english: "ceiling", chinese: "天花板" },
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 10", english: "floor", chinese: "地板" },
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 10", english: "basket", chinese: "籃子" },
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 10", english: "toolbox", chinese: "工具箱" },

  // TEAMMS 6, Lesson 11
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 11", english: "knight", chinese: "騎士" },
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 11", english: "prince", chinese: "王子" },
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 11", english: "princess", chinese: "公主" },
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 11", english: "witch", chinese: "巫婆" },
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 11", english: "queen", chinese: "皇后" },
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 11", english: "king", chinese: "國王" },
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 11", english: "wizard", chinese: "巫師" },
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 11", english: "clown", chinese: "小丑" },
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 11", english: "alien", chinese: "外星人" },
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 11", english: "monster", chinese: "怪物" },

  // TEAMMS 6, Lesson 12
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 12", english: "morning (5AM~12PM)", chinese: "早上" },
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 12", english: "at noon (12PM)", chinese: "中午" },
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 12", english: "afternoon (12PM~5PM)", chinese: "下午" },
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 12", english: "evening (5PM~8PM)", chinese: "傍晚" },
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 12", english: "at night (8PM~5AM)", chinese: "在晚上" },
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 12", english: "midnight (12AM)", chinese: "午夜" },
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 12", english: "tonight", chinese: "今晚" },
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 12", english: "yesterday", chinese: "昨天" },
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 12", english: "last night", chinese: "昨晚" },
  { id: generateId(), team: "TEAMMS 6", lesson: "Lesson 12", english: "the day before yesterday", chinese: "前天" },

  // TEAMMS 7, Lesson 1
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 1", english: "quietly", chinese: "安靜地" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 1", english: "loudly", chinese: "大聲地" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 1", english: "slowly", chinese: "緩慢地" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 1", english: "quickly", chinese: "很快地" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 1", english: "easily", chinese: "簡單地" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 1", english: "happily", chinese: "開心地" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 1", english: "badly", chinese: "糟糕地" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 1", english: "carefully", chinese: "小心地" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 1", english: "well", chinese: "很好地" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 1", english: "hard", chinese: "努力地" },

  // TEAMMS 7, Lesson 2
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 2", english: "breakfast", chinese: "早餐" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 2", english: "lunch", chinese: "午餐" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 2", english: "dinner", chinese: "晚餐" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 2", english: "a cup of yogurt", chinese: "一杯優格" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 2", english: "a piece of toast", chinese: "一片吐司" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 2", english: "a slice of bacon", chinese: "一片培根" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 2", english: "a fried egg", chinese: "一個煎蛋" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 2", english: "a bowl of porridge", chinese: "一碗稀飯" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 2", english: "a pancake", chinese: "一個薄煎餅" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 2", english: "a doughnut", chinese: "一個甜甜圈" },

  // TEAMMS 7, Lesson 3
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 3", english: "shoulder", chinese: "肩膀" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 3", english: "neck", chinese: "脖子" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 3", english: "toe", chinese: "腳趾頭" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 3", english: "thumb", chinese: "拇指" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 3", english: "ankle", chinese: "腳踝" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 3", english: "knee", chinese: "膝蓋" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 3", english: "hand", chinese: "手" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 3", english: "finger", chinese: "手指頭" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 3", english: "foot", chinese: "腳" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 3", english: "elbow", chinese: "手肘" },

  // TEAMMS 7, Lesson 4
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 4", english: "jeans", chinese: "牛仔褲" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 4", english: "cardigan", chinese: "開襟衫" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 4", english: "tank top", chinese: "背心" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 4", english: "stockings", chinese: "長襪" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 4", english: "leggings", chinese: "內搭褲" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 4", english: "coat", chinese: "大衣" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 4", english: "sweatpants", chinese: "運動褲" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 4", english: "blouse", chinese: "短衫" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 4", english: "bright", chinese: "亮的" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 4", english: "colorful", chinese: "多彩的" },

  // TEAMMS 7, Lesson 5
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 5", english: "January", chinese: "一月" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 5", english: "February", chinese: "二月" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 5", english: "March", chinese: "三月" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 5", english: "April", chinese: "四月" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 5", english: "May", chinese: "五月" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 5", english: "June", chinese: "六月" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 5", english: "July", chinese: "七月" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 5", english: "August", chinese: "八月" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 5", english: "September", chinese: "九月" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 5", english: "October", chinese: "十月" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 5", english: "November", chinese: "十一月" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 5", english: "December", chinese: "十二月" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 5", english: "month", chinese: "月份" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 5", english: "year", chinese: "年" },

  // TEAMMS 7, Lesson 6
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 6", english: "cupboard", chinese: "櫥櫃" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 6", english: "refrigerator", chinese: "冰箱" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 6", english: "armchair", chinese: "扶手椅" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 6", english: "window", chinese: "窗戶" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 6", english: "drawer", chinese: "抽屜" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 6", english: "dresser", chinese: "梳妝台" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 6", english: "cabinet", chinese: "櫥櫃" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 6", english: "bookcase", chinese: "書櫃" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 6", english: "trunk", chinese: "行李箱" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 6", english: "wardrobe", chinese: "衣櫃" },

  // TEAMMS 7, Lesson 7
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 7", english: "sleep, slept", chinese: "睡覺" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 7", english: "read, read", chinese: "閱讀" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 7", english: "swim, swam", chinese: "游泳" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 7", english: "stand, stood", chinese: "站" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 7", english: "make, made", chinese: "製作" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 7", english: "write, wrote", chinese: "寫" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 7", english: "sit, sat", chinese: "坐" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 7", english: "run, ran", chinese: "跑" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 7", english: "draw, drew", chinese: "畫畫" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 7", english: "drive, drove", chinese: "駕駛" },

  // TEAMMS 7, Lesson 8
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 8", english: "wake up, woke up", chinese: "起床" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 8", english: "spend, spent", chinese: "花費" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 8", english: "leave, left", chinese: "留" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 8", english: "see, saw", chinese: "看到" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 8", english: "hear, heard", chinese: "聽到" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 8", english: "give, gave", chinese: "給" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 8", english: "keep, kept", chinese: "保留" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 8", english: "think, thought", chinese: "思考" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 8", english: "choose, chose", chinese: "選擇" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 8", english: "begin, began", chinese: "開始" },

  // TEAMMS 7, Lesson 9
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 9", english: "come, came", chinese: "來" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 9", english: "become, became", chinese: "變成" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 9", english: "bring, brought", chinese: "帶來" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 9", english: "throw, threw", chinese: "丟" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 9", english: "fly, flew", chinese: "飛" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 9", english: "break, broke", chinese: "打破" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 9", english: "teach, taught", chinese: "教" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 9", english: "win, won", chinese: "贏" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 9", english: "grow, grew", chinese: "生長" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 9", english: "catch, caught", chinese: "抓" },

  // TEAMMS 7, Lesson 10
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 10", english: "steal, stole", chinese: "偷" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 10", english: "bite, bit", chinese: "咬" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 10", english: "buy, bought", chinese: "買" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 10", english: "tear, tore", chinese: "撕" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 10", english: "tell, told", chinese: "告訴" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 10", english: "sing, sang", chinese: "唱歌" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 10", english: "say, said", chinese: "說" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 10", english: "ride, rode", chinese: "騎" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 10", english: "meet, met", chinese: "見面" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 10", english: "lie, lay", chinese: "躺" },

  // TEAMMS 7, Lesson 11
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 11", english: "cook, cooked", chinese: "烹飪" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 11", english: "ask, asked", chinese: "詢問" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 11", english: "watch, watched", chinese: "看" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 11", english: "play, played", chinese: "玩" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 11", english: "listen, listened", chinese: "聽" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 11", english: "stop, stopped", chinese: "停止" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 11", english: "collect, collected", chinese: "收集" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 11", english: "clean, cleaned", chinese: "清理" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 11", english: "try, tried", chinese: "嘗試" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 11", english: "study, studied", chinese: "讀書" },

  // TEAMMS 7, Lesson 12
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 12", english: "Halloween", chinese: "萬聖節" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 12", english: "Christmas", chinese: "聖誕節" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 12", english: "Valentine's Day", chinese: "情人節" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 12", english: "Easter", chinese: "復活節" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 12", english: "Mother's Day", chinese: "母親節" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 12", english: "Father's Day", chinese: "父親節" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 12", english: "New Year's Day", chinese: "元旦" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 12", english: "Thanksgiving", chinese: "感恩節" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 12", english: "Chinese New Year", chinese: "中國新年" },
  { id: generateId(), team: "TEAMMS 7", lesson: "Lesson 12", english: "decorate", chinese: "佈置/裝飾" },

  // TEAMMS 8, Lesson 1
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 1", english: "fox", chinese: "狐狸" },
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 1", english: "zebra", chinese: "斑馬" },
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 1", english: "turtle", chinese: "烏龜" },
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 1", english: "alligator", chinese: "鱷魚" },
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 1", english: "eagle", chinese: "老鷹" },
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 1", english: "cockroach", chinese: "蟑螂" },
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 1", english: "lizard", chinese: "蜥蜴" },
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 1", english: "mosquito", chinese: "蚊子" },
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 1", english: "worm", chinese: "蟲" },
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 1", english: "caterpillar", chinese: "毛毛蟲" },

  // TEAMMS 8, Lesson 2
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 2", english: "curtains", chinese: "窗簾" },
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 2", english: "candle", chinese: "蠟燭" },
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 2", english: "poster", chinese: "海報" },
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 2", english: "vase", chinese: "花瓶" },
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 2", english: "drapes", chinese: "窗簾" },
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 2", english: "purse", chinese: "錢包" },
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 2", english: "hanger", chinese: "衣架" },
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 2", english: "trash can", chinese: "垃圾桶" },
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 2", english: "expensive", chinese: "貴的" },
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 2", english: "picture frame", chinese: "相框" },

  // TEAMMS 8, Lesson 3
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 3", english: "thigh", chinese: "大腿" },
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 3", english: "waist", chinese: "腰部" },
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 3", english: "hip", chinese: "臀部" },
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 3", english: "chin", chinese: "下巴" },
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 3", english: "tongue", chinese: "舌頭" },
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 3", english: "wrist", chinese: "手腕" },
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 3", english: "fingernail", chinese: "手指甲" },
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 3", english: "tooth", chinese: "牙齒" },
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 3", english: "hair", chinese: "頭髮" },
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 3", english: "toenail", chinese: "腳指甲" },

  // TEAMMS 8, Lesson 4
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 4", english: "talkative", chinese: "健談的" },
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 4", english: "embarrassed", chinese: "尷尬的" },
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 4", english: "comfortable", chinese: "自在的" },
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 4", english: "careless", chinese: "粗心的" },
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 4", english: "dangerous", chinese: "危險的" },
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 4", english: "careful", chinese: "小心的" },
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 4", english: "nervous", chinese: "緊張的" },
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 4", english: "handsome", chinese: "英俊的" },
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 4", english: "cheerful", chinese: "愉快的" },
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 4", english: "serious", chinese: "嚴肅的/認真的/嚴重的" },

  // TEAMMS 8, Lesson 5
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 5", english: "classmates", chinese: "同學" },
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 5", english: "interesting", chinese: "有趣的" },
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 5", english: "boyfriend", chinese: "男朋友" },
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 5", english: "awesome", chinese: "出色的" },
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 5", english: "girlfriend", chinese: "女朋友" },
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 5", english: "concert hall", chinese: "音樂廳" },
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 5", english: "wonderful", chinese: "極好的/完美的/精彩的" },
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 5", english: "awful", chinese: "糟糕的" },
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 5", english: "surprising", chinese: "驚人的" },
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 5", english: "strange", chinese: "奇怪的" },

  // TEAMMS 8, Lesson 6
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 6", english: "spring", chinese: "春天" },
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 6", english: "camping", chinese: "露營" },
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 6", english: "summer", chinese: "夏天" },
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 6", english: "fishing", chinese: "釣魚" },
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 6", english: "winter", chinese: "冬天" },
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 6", english: "surfing", chinese: "衝浪" },
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 6", english: "fall", chinese: "秋天" },
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 6", english: "cycling", chinese: "腳踏車" },
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 6", english: "hiking", chinese: "健行" },
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 6", english: "skiing", chinese: "滑雪" },

  // TEAMMS 8, Lesson 7
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 7", english: "sunscreen", chinese: "防曬霜" },
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 7", english: "sleeping bag", chinese: "睡袋" },
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 7", english: "trail", chinese: "小徑" },
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 7", english: "matches", chinese: "火柴" },
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 7", english: "flashlight", chinese: "手電筒" },
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 7", english: "compass", chinese: "指南針" },
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 7", english: "insect repellent", chinese: "驅蟲劑" },
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 7", english: "cabin", chinese: "小木屋" },
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 7", english: "hammock", chinese: "吊床" },
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 7", english: "camping gear", chinese: "露營裝備" },

  // TEAMMS 8, Lesson 8
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 8", english: "broccoli", chinese: "花椰菜" },
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 8", english: "asparagus", chinese: "蘆筍" },
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 8", english: "bean", chinese: "豆" },
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 8", english: "cauliflower", chinese: "花椰菜" },
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 8", english: "garlic", chinese: "大蒜" },
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 8", english: "eggplant", chinese: "茄子" },
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 8", english: "spinach", chinese: "菠菜" },
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 8", english: "ginger", chinese: "薑" },
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 8", english: "celery", chinese: "芹菜" },
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 8", english: "grocery shopping", chinese: "雜貨店購物" },

  // TEAMMS 8, Lesson 9
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 9", english: "soft", chinese: "柔軟的" },
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 9", english: "rough", chinese: "粗的" },
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 9", english: "hard", chinese: "硬的" },
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 9", english: "shiny", chinese: "閃亮的" },
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 9", english: "bumpy", chinese: "顛簸的" },
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 9", english: "sticky", chinese: "黏性的" },
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 9", english: "smooth", chinese: "光滑的" },
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 9", english: "crooked", chinese: "歪的" },
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 9", english: "straight", chinese: "直的" },
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 9", english: "flat", chinese: "平的" },

  // TEAMMS 8, Lesson 10
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 10", english: "talented", chinese: "有才能的" },
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 10", english: "athletic", chinese: "擅長運動的" },
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 10", english: "brave", chinese: "勇敢的" },
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 10", english: "loving", chinese: "愛的" },
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 10", english: "curious", chinese: "好奇的" },
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 10", english: "moody", chinese: "心情多變的" },
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 10", english: "creative", chinese: "有創造力的" },
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 10", english: "crazy", chinese: "瘋狂的" },
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 10", english: "loyal", chinese: "忠誠的" },
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 10", english: "helpful", chinese: "有幫助的" },

  // TEAMMS 8, Lesson 11
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 11", english: "eating out", chinese: "在外用餐" },
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 11", english: "building things", chinese: "建造東西" },
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 11", english: "learning origami", chinese: "學習摺紙" },
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 11", english: "spending time alone / with", chinese: "花時間單獨/與" },
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 11", english: "knitting", chinese: "編織" },
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 11", english: "daydreaming", chinese: "做白日夢" },
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 11", english: "chatting", chinese: "聊天" },
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 11", english: "meeting new people", chinese: "認識新朋友" },
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 11", english: "traveling", chinese: "旅行" },
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 11", english: "dressing up", chinese: "打扮" },

  // TEAMMS 8, Lesson 12
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 12", english: "coding", chinese: "編碼" },
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 12", english: "finding things online", chinese: "在網上找東西" },
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 12", english: "planning", chinese: "規劃" },
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 12", english: "making friends", chinese: "交朋友" },
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 12", english: "storytelling", chinese: "講故事" },
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 12", english: "making decisions", chinese: "做決定" },
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 12", english: "writing stories", chinese: "寫故事" },
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 12", english: "talking to people", chinese: "與人交談" },
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 12", english: "public speaking", chinese: "公開演講" },
  { id: generateId(), team: "TEAMMS 8", lesson: "Lesson 12", english: "solving problems", chinese: "解決問題" },

  // TEAMMS 9, Lesson 1
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 1", english: "gardening", chinese: "園藝" },
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 1", english: "walking the dog", chinese: "遛狗" },
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 1", english: "fixing my hair", chinese: "整理頭髮" },
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 1", english: "charging my phone", chinese: "手機充電" },
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 1", english: "doing my makeup", chinese: "化妝" },
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 1", english: "finishing a project", chinese: "完成一個項目" },
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 1", english: "ironing my shirt", chinese: "熨襯衫" },
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 1", english: "downloading / uploading photos", chinese: "下載/上傳照片" },
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 1", english: "reading a novel", chinese: "閱讀小說" },
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 1", english: "installing an app", chinese: "安裝應用程式" },

  // TEAMMS 9, Lesson 2
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 2", english: "preparing for a trip", chinese: "準備旅行" },
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 2", english: "practicing my speech", chinese: "練習我的演講" },
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 2", english: "reading a magazine", chinese: "閱讀雜誌" },
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 2", english: "typing a school report", chinese: "輸入學校報告" },
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 2", english: "flossing my teeth", chinese: "用牙線剔牙" },
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 2", english: "organizing my files", chinese: "整理檔案" },
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 2", english: "taking a nap", chinese: "睡一小會兒" },
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 2", english: "attending a wedding", chinese: "參加婚禮" },
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 2", english: "relaxing at home", chinese: "在家放鬆" },
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 2", english: "discussing a problem", chinese: "討論問題" },

  // TEAMMS 9, Lesson 3
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 3", english: "excited about", chinese: "興奮" },
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 3", english: "afraid of / scared of", chinese: "害怕" },
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 3", english: "bored with / bored of", chinese: "無聊" },
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 3", english: "skateboarding", chinese: "滑板運動" },
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 3", english: "tired of", chinese: "厭倦" },
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 3", english: "skydiving", chinese: "跳傘" },
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 3", english: "worried about", chinese: "擔心" },
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 3", english: "rock climbing", chinese: "攀岩" },
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 3", english: "interested in", chinese: "有興趣" },
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 3", english: "snorkeling", chinese: "浮潛" },

  // TEAMMS 9, Lesson 4
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 4", english: "physics", chinese: "物理" },
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 4", english: "biology", chinese: "生物" },
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 4", english: "science", chinese: "科學" },
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 4", english: "geography", chinese: "地理" },
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 4", english: "social studies", chinese: "社會" },
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 4", english: "chemistry", chinese: "化學" },
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 4", english: "language arts", chinese: "語言藝術" },
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 4", english: "art", chinese: "藝術" },
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 4", english: "history", chinese: "歷史" },
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 4", english: "physical education (PE)", chinese: "體育" },

  // TEAMMS 9, Lesson 5
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 5", english: "tired, tiring", chinese: "疲勞的, 令人疲倦的" },
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 5", english: "shocked, shocking", chinese: "震驚的, 令人震驚的" },
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 5", english: "thrilled, thrilling", chinese: "非常興奮的, 令人興奮的" },
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 5", english: "frightened, frightening", chinese: "受驚的, 令人恐懼的" },
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 5", english: "excited, exciting", chinese: "興奮的, 令人興奮的" },
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 5", english: "disgusted, disgusting", chinese: "噁心的, 令人噁心的" },
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 5", english: "relaxed, relaxing", chinese: "放鬆的, 令人放鬆的" },
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 5", english: "disappointed, disappointing", chinese: "失望的, 令人失望的" },
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 5", english: "annoyed, annoying", chinese: "惱人的, 令人惱人的" },
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 5", english: "amazed, amazing", chinese: "驚奇的, 令人驚奇的" },

  // TEAMMS 9, Lesson 6
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 6", english: "comedy", chinese: "喜劇片" },
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 6", english: "hero", chinese: "英雄" },
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 6", english: "action movie", chinese: "動作片" },
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 6", english: "heroine", chinese: "女英雄" },
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 6", english: "horror movie", chinese: "恐怖片" },
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 6", english: "villain", chinese: "壞人" },
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 6", english: "romance movie", chinese: "浪漫片" },
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 6", english: "weak", chinese: "虛弱的" },
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 6", english: "science fiction movie", chinese: "科幻片" },
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 6", english: "powerful", chinese: "強大的" },

  // TEAMMS 9, Lesson 7
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 7", english: "chew loudly", chinese: "大聲咀嚼" },
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 7", english: "stare", chinese: "盯" },
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 7", english: "blow your nose", chinese: "擤鼻涕" },
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 7", english: "slurp", chinese: "出聲地喝" },
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 7", english: "slam the door", chinese: "甩門" },
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 7", english: "burp", chinese: "打嗝" },
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 7", english: "hold the door", chinese: "抓住門" },
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 7", english: "polite", chinese: "有禮貌的" },
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 7", english: "interrupt", chinese: "打斷" },
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 7", english: "rude", chinese: "無禮的" },

  // TEAMMS 9, Lesson 8
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 8", english: "India, Hindi", chinese: "印度, 印度語" },
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 8", english: "Germany, German", chinese: "德國, 德文" },
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 8", english: "Russia, Russian", chinese: "俄羅斯, 俄語" },
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 8", english: "Japan, Japanese", chinese: "日本, 日文" },
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 8", english: "Mexico, Spanish", chinese: "墨西哥, 西班牙文" },
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 8", english: "France, French", chinese: "法國, 法文" },
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 8", english: "United Kingdom, English", chinese: "英國, 英文" },
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 8", english: "Italy, Italian", chinese: "義大利, 義大利文" },
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 8", english: "Brazil, Portuguese", chinese: "巴西, 葡萄牙文" },
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 8", english: "Egypt, Arabic", chinese: "埃及, 阿拉伯文" },

  // TEAMMS 9, Lesson 9
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 9", english: "musician", chinese: "音樂家" },
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 9", english: "hairdresser", chinese: "髮型師" },
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 9", english: "professor", chinese: "教授" },
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 9", english: "pilot", chinese: "飛行員" },
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 9", english: "reporter", chinese: "記者" },
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 9", english: "coach", chinese: "教練" },
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 9", english: "mechanic", chinese: "技師" },
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 9", english: "waiter", chinese: "服務生" },
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 9", english: "flight attendant", chinese: "空服人員" },
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 9", english: "waitress", chinese: "女服務生" },

  // TEAMMS 9, Lesson 10
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 10", english: "body wash", chinese: "沐浴乳" },
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 10", english: "earrings", chinese: "耳環" },
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 10", english: "shampoo / conditioner", chinese: "洗髮精/潤髮乳" },
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 10", english: "watch", chinese: "手錶" },
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 10", english: "air conditioner", chinese: "冷氣" },
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 10", english: "handkerchief", chinese: "手帕" },
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 10", english: "heater", chinese: "暖爐" },
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 10", english: "wallet", chinese: "皮夾" },
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 10", english: "newspaper", chinese: "報紙" },
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 10", english: "perfume", chinese: "香水" },

  // TEAMMS 9, Lesson 11
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 11", english: "smartphone", chinese: "智慧型手機" },
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 11", english: "headphones", chinese: "耳機" },
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 11", english: "charger", chinese: "充電器" },
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 11", english: "website", chinese: "網站" },
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 11", english: "tablet", chinese: "掌上電腦" },
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 11", english: "video game", chinese: "電子遊戲" },
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 11", english: "e-book", chinese: "電子書" },
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 11", english: "texting", chinese: "傳簡訊" },
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 11", english: "speaker", chinese: "喇叭" },
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 11", english: "shopping online", chinese: "線上購物" },

  // TEAMMS 9, Lesson 12
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 12", english: "write, wrote, written", chinese: "寫" },
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 12", english: "make, made, made", chinese: "製作" },
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 12", english: "see, saw, seen", chinese: "看見" },
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 12", english: "go, went, gone", chinese: "去" },
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 12", english: "am, was, been", chinese: "是" },
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 12", english: "live, lived, lived", chinese: "住" },
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 12", english: "do, did, done", chinese: "做" },
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 12", english: "become, became, become", chinese: "變成" },
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 12", english: "give, gave, given", chinese: "給" },
  { id: generateId(), team: "TEAMMS 9", lesson: "Lesson 12", english: "keep, kept, kept", chinese: "保持" },
];